git:
  depth: 3
language: java
jdk:
  - oraclejdk11
services:
  - postgresql
before_install:
  - psql -c 'create database spring;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD '1234';" -U postgres
  - psql -c 'create table factura(numero int primary key, concepto character varying(5), importe numeric);' -U postgres
#before_install:
#  - chmod +x ./mvnw
